version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        platform: amd64
        TARGETOS: linux
        TARGETARCH: amd64
        GOARCH: amd64
    platform: linux/arm64
    ports:
      - "8080:8080"