# Generated by Django 4.2.13 on 2024-07-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOPcardAPI_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('pos_z', models.FloatField()),
                ('rot_x', models.FloatField()),
                ('rot_y', models.FloatField()),
                ('rot_z', models.FloatField()),
                ('rl', models.CharField(max_length=100)),
            ],
        ),
    ]
