# Generated by Django 4.2.13 on 2024-07-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOPcardAPI_app', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='LR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rl', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='rl',
        ),
    ]
